//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championship
    {
        public Championship()
        {
            this.Journey = new HashSet<Journey>();
            this.Season = new HashSet<Season>();
            this.TeamPoints = new HashSet<TeamPoints>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public System.DateTime FoudationDate { get; set; }
        public int CountryID { get; set; }
        public int EntityMngID { get; set; }
    
        public virtual EntityManager EntityManager { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Journey> Journey { get; set; }
        public virtual ICollection<Season> Season { get; set; }
        public virtual ICollection<TeamPoints> TeamPoints { get; set; }
    }
}
