//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Country
    {
        public Country()
        {
            this.Championship = new HashSet<Championship>();
            this.Player = new HashSet<Player>();
            this.Team = new HashSet<Team>();
        }
    
        public int ID { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Country name cannot have more than 50 characters")]
        public string Name { get; set; }
    
        public virtual ICollection<Championship> Championship { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
