//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Championship = new HashSet<Championship>();
            this.City = new HashSet<City>();
            this.Player = new HashSet<Player>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Championship> Championship { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Player> Player { get; set; }
    }
}
