//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EntityManager
    {
        public EntityManager()
        {
            this.Championship = new HashSet<Championship>();
        }
    
        public int ID { get; set; }

        [Required]
        [StringLength(150, ErrorMessage = "The Name cannot have more than 50 characters")]
        public string Name { get; set; }
    
        public virtual ICollection<Championship> Championship { get; set; }
    }
}
