//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MatchGoals
    {
        public int ID { get; set; }

        [Required]
        public int MatchID { get; set; }

        [Required]
        public int TeamID { get; set; }

        [Required]
        public int PlayerID { get; set; }

        [Required]
        //[DataType(DataType.Time, ErrorMessage = "Please enter a valid date")]
        //[DisplayFormat(DataFormatString = "{0:mm\\:ss}", ApplyFormatInEditMode = true)]
        [RegularExpression("^(00:[0-5][1-9])|(([1-119]){1,3}:([0-5][0-9]))|(120:00)$", ErrorMessage = "Please enter a valid time, between 00:01 and 120:00")]
        public System.DateTime Time { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
