//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int ID { get; set; }
        public int ChampshipID { get; set; }
        public System.DateTime Year { get; set; }
        public int NumberOfTeams { get; set; }
    
        public virtual Championship Championship { get; set; }
    }
}
