//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Match = new HashSet<Match>();
            this.Match1 = new HashSet<Match>();
            this.Player = new HashSet<Player>();
            this.TeamPoints = new HashSet<TeamPoints>();
            this.MatchGoals = new HashSet<MatchGoals>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public System.DateTime FundationDate { get; set; }
        public int CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Match> Match { get; set; }
        public virtual ICollection<Match> Match1 { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<TeamPoints> TeamPoints { get; set; }
        public virtual ICollection<MatchGoals> MatchGoals { get; set; }
    }
}
