//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    
    public partial class Team
    {
        public Team()
        {
            this.Match = new HashSet<Match>();
            this.Match1 = new HashSet<Match>();
            this.MatchGoals = new HashSet<MatchGoals>();
            this.Player = new HashSet<Player>();
            this.TeamPoints = new HashSet<TeamPoints>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }

        public string Logo { get; set; }

        //[Required]
        [NotMapped]
        [DataType(DataType.Upload)]
        //[FileSize(10240)]
        //[FileTypes("jpg,jpeg,png,gif")]
        public HttpPostedFileBase LogoPath { get; set; }
                
        public System.DateTime FundationDate { get; set; }
        public int CountryID { get; set; }
        public string City { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Match> Match { get; set; }
        public virtual ICollection<Match> Match1 { get; set; }
        public virtual ICollection<MatchGoals> MatchGoals { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<TeamPoints> TeamPoints { get; set; }
    }
}
